#!/usr/bin/env node

/**
 * Bundles the audit's parser — acorn with @sveltejs/acorn-typescript — into one
 * committed file inside the skill.
 *
 * The skill can depend on nothing. It is installed by copying a folder from
 * git, the npm package may not declare dependencies, and CI's test job runs
 * with no install. So the parser is vendored: generated from the versions the
 * root package.json pins, and checked in. `--check` regenerates it in memory
 * and fails when the committed file differs, so a bump that is not followed by
 * a regeneration cannot leave the skill parsing with the old version.
 *
 * Minified, because every project that installs the skill carries a copy. The
 * header names each package, version and licence; the licence texts are in the
 * skill's NOTICE.md.
 *
 *   node scripts/vendor-parser.mjs          # write the file
 *   node scripts/vendor-parser.mjs --check  # exit 1 when it is out of date
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

import { build } from "esbuild";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(
  ROOT,
  "plugins/gsap-motion/skills/gsap-creative-animation/scripts/lib/vendor/parser.mjs",
);
const PACKAGES = ["acorn", "@sveltejs/acorn-typescript"];

const readJson = (path) => JSON.parse(readFileSync(path, "utf8"));
const pinned = readJson(join(ROOT, "package.json")).devDependencies ?? {};
const installed = Object.fromEntries(
  PACKAGES.map((name) => [
    name,
    readJson(join(ROOT, "node_modules", name, "package.json")),
  ]),
);

for (const name of PACKAGES) {
  if (pinned[name] !== installed[name].version) {
    console.error(
      `${name}: package.json pins ${pinned[name] ?? "nothing"}, node_modules has ${installed[name].version}. Run npm ci first.`,
    );
    process.exit(1);
  }
}

const banner = [
  "// Generated by scripts/vendor-parser.mjs from the root package.json's pinned",
  "// devDependencies. Do not edit: change the pin and regenerate.",
  `// ${PACKAGES.map((name) => `${name} ${installed[name].version} (${installed[name].license})`).join("; ")}`,
  "// Licence texts: NOTICE.md in the skill.",
].join("\n");

const result = await build({
  stdin: {
    contents: `export { Parser } from "acorn";\nexport { tsPlugin } from "@sveltejs/acorn-typescript";\n`,
    resolveDir: ROOT,
    loader: "js",
  },
  bundle: true,
  write: false,
  format: "esm",
  platform: "neutral",
  mainFields: ["module", "main"],
  target: "node18",
  minify: true,
  legalComments: "none",
  banner: { js: banner },
  logLevel: "silent",
});

const code = result.outputFiles[0].text.replace(/\r\n/g, "\n");
const shown = relative(ROOT, OUT).replace(/\\/g, "/");

if (process.argv.includes("--check")) {
  const current = existsSync(OUT)
    ? readFileSync(OUT, "utf8").replace(/\r\n/g, "\n")
    : "";
  if (current !== code) {
    console.error(
      `${shown} is out of date. Run \`node scripts/vendor-parser.mjs\` and commit the result.`,
    );
    process.exit(1);
  }
  console.log(`${shown} matches its pinned sources.`);
} else {
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, code);
  console.log(`Wrote ${shown} (${(Buffer.byteLength(code) / 1024).toFixed(0)} KB).`);
}
